version: '3.4'

services: 
  db:
    image: "postgres:12.4"
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
        context: .
        dockerfile: Dockerfile.dev
    volumes: 
      - ./:/app
    ports: 
      - ${PORT}:${PORT}
    depends_on:
      - db
volumes: 
    pgdata:
    