# Generated by Django 3.2.3 on 2021-06-30 23:28

import API.customers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('status_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'BodyAttribute',
                'verbose_name_plural': 'BodyAttributes',
                'db_table': 'bodyAttribute',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BodyAttribute_HistoryClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='Sin dato', max_length=255)),
                ('status_delete', models.BooleanField(default=False)),
                ('bodyAttribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.bodyattribute')),
            ],
            options={
                'verbose_name': 'BodyAttribute_HistoryClinic',
                'verbose_name_plural': 'BodyAttribute_HistoryClinics',
                'db_table': 'bodyAttribute_historyClinic',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('phone', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, default='default.jpg', max_length=255, null=True, upload_to=API.customers.models.upload_load)),
                ('membershipActivate', models.BooleanField(default=False)),
                ('isStudiant', models.BooleanField(default=False)),
                ('dateJoined', models.DateField(auto_now=True, verbose_name='Fecha de registro')),
                ('status_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoryClinic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('age', models.SmallIntegerField()),
                ('weigth', models.PositiveBigIntegerField()),
                ('heigh', models.PositiveIntegerField()),
                ('bloodType', models.CharField(choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], default='O+', max_length=4)),
                ('status_delete', models.BooleanField(default=False)),
                ('bodyAttribute', models.ManyToManyField(through='customers.BodyAttribute_HistoryClinic', to='customers.BodyAttribute')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name': 'HistoryClinic',
                'verbose_name_plural': 'HistoryClinics',
                'db_table': 'historyClinic',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NutritionalSituation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hour_breakfast', models.TimeField(blank=True, null=True)),
                ('hour_collation', models.TimeField(blank=True, null=True)),
                ('hour_lunch', models.TimeField(blank=True, null=True)),
                ('hour_snack', models.TimeField(blank=True, null=True)),
                ('hour_dinner', models.TimeField(blank=True, null=True)),
                ('schedule', models.TextField(blank=True, max_length=100, null=True)),
                ('status_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'NutritionalSituation',
                'verbose_name_plural': 'NutritionalSituations',
                'db_table': 'nutritionalSituation',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypeExtraInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('status_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'TypeExtraInformation',
                'verbose_name_plural': 'TypeExtraInformations',
                'db_table': 'typeExtraInformation',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypeExtraInformation_HistoryClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.BooleanField(default=False)),
                ('status_delete', models.BooleanField(default=False)),
                ('historyClinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.historyclinic')),
                ('typeExtraInformation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.typeextrainformation')),
            ],
            options={
                'verbose_name': 'TypeExtraInformation_HistoryClinic',
                'verbose_name_plural': 'TypeExtraInformation_HistoryClinics',
                'db_table': 'typeExtraInformation_historyClinic',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='historyclinic',
            name='nutritionalSituation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.nutritionalsituation'),
        ),
        migrations.AddField(
            model_name='historyclinic',
            name='typeExtraInformation',
            field=models.ManyToManyField(through='customers.TypeExtraInformation_HistoryClinic', to='customers.TypeExtraInformation'),
        ),
        migrations.CreateModel(
            name='Customer_Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_register', models.DateField(auto_now=True, verbose_name='Fecha de registro')),
                ('date_due', models.DateField(verbose_name='Fecha de vencimiento')),
                ('valid', models.BooleanField(default=True)),
                ('status_delete', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('membership_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.membership')),
            ],
            options={
                'verbose_name': 'Customer_Membership',
                'verbose_name_plural': 'Customer_Memberships',
                'db_table': 'customer_Membership',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.ManyToManyField(through='customers.Customer_Membership', to='memberships.Membership'),
        ),
        migrations.AddField(
            model_name='bodyattribute_historyclinic',
            name='historyClinic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.historyclinic'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha de asistencia')),
                ('check_in', models.TimeField(auto_now_add=True, verbose_name='Hora de entrada')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('status_delete', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendance',
                'ordering': ['id'],
            },
        ),
    ]
