# Generated by Django 3.2.3 on 2021-06-30 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('status_delete', models.BooleanField(default=False, verbose_name='Status Delete')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'Module',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('isSuperAdmin', models.BooleanField(default=False, verbose_name='Super admin')),
                ('status_delete', models.BooleanField(default=False, verbose_name='Status Delete')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'Role',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RoleModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status Delete')),
                ('status_delete', models.BooleanField(default=False, verbose_name='Status Delete')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.module', verbose_name='Id del Modulo')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.role', verbose_name='Id del Rol')),
            ],
            options={
                'verbose_name': 'Role_Module',
                'verbose_name_plural': 'Role_Modules',
                'db_table': 'Role_Module',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='role',
            name='module',
            field=models.ManyToManyField(through='general.RoleModule', to='general.Module'),
        ),
    ]
