# Generated by Django 3.2.3 on 2021-07-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='cambio',
            field=models.FloatField(default=0, null=True),
        ),
    ]
